#For YML files can only use single line comment with symbol "#"
#This YML file is commonly used for configuration files and in applications where data is being stored or transmitted. 

#########################################
####     Email Server Setting        ####
#########################################


spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: toughguy5678@gmail.com
spring.mail.password: 12345678qaz
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
mail.smtp.debug: true

#########################################
####        Database setting         ####
#########################################
spring.datasource.url: jdbc:mysql://seralock-db.cwhxcgdndstk.us-east-2.rds.amazonaws.com:3306/evntmgmt_usa
spring.datasource.username: evntmgmt-usa
spring.datasource.password: Dbdev@Enfec15
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#60 sec
spring.datasource.hikari.connection-timeout: 60000
# max 3
spring.datasource.hikari.maximum-pool-size: 3