#For YML files can only use single line comment with symbol "#"
#This YML file is commonly used for configuration files and in applications where data is being stored or transmitted. 


spring.datasource.url: jdbc:mysql://seralock-db.cwhxcgdndstk.us-east-2.rds.amazonaws.com:3306/evntmgmt_usa?serverTimezone=UTC
spring.datasource.username: evntmgmt-usa
spring.datasource.password: Dbdev@Enfec15
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#60 sec
spring.datasource.hikari.connection-timeout: 60000
# max 5
spring.datasource.hikari.maximum-pool-size: 3